const basededados = {
    "ingles": [
        { "frase": "O céu está muito bonito hoje.", "traducao": "The sky is very beautiful today." },
        { "frase": "Eu gosto de aprender coisas novas.", "traducao": "I like to learn new things." },
        { "frase": "Onde fica a biblioteca?", "traducao": "Where is the library?" },
        { "frase": "Eu preciso de um café.", "traducao": "I need a coffee." },
        { "frase": "Qual é o seu livro favorito?", "traducao": "What is your favorite book?" },
        { "frase": "Eu esqueci de responder o e-mail ontem.", "traducao": "I forgot to reply to the email yesterday." },
{ "frase": "Ela está tentando aprender uma nova habilidade.", "traducao": "She is trying to learn a new skill." },
{ "frase": "Nós precisamos tomar uma decisão em breve.", "traducao": "We need to make a decision soon." },
{ "frase": "Ele ficou surpreso com o resultado da reunião.", "traducao": "He was surprised by the outcome of the meeting." },
{ "frase": "Eu não concordo totalmente com essa ideia.", "traducao": "I don’t completely agree with this idea." },
{ "frase": "Eles cancelaram a viagem por causa do clima.", "traducao": "They canceled the trip because of the weather." },
{ "frase": "Estou procurando uma solução mais eficiente.", "traducao": "I am looking for a more efficient solution." },
{ "frase": "Ela se sente confiante sobre a apresentação.", "traducao": "She feels confident about the presentation." },
{ "frase": "Nós acabamos perdendo o último ônibus.", "traducao": "We ended up missing the last bus." },
{ "frase": "Ele prefere trabalhar sozinho à noite.", "traducao": "He prefers to work alone at night." },
{ "frase": "Eu percebi um erro no relatório.", "traducao": "I noticed a mistake in the report." },
{ "frase": "Ela explicou a situação com muita clareza.", "traducao": "She explained the situation very clearly." },
{ "frase": "Nós estamos acostumados a lidar com pressão.", "traducao": "We are used to dealing with pressure." },
{ "frase": "Ele hesitou antes de aceitar a proposta.", "traducao": "He hesitated before accepting the offer." },
{ "frase": "Eu estou tentando equilibrar trabalho e vida pessoal.", "traducao": "I am trying to balance work and personal life." },
{ "frase": "Ela ficou frustrada com a falta de progresso.", "traducao": "She got frustrated with the lack of progress." },
{ "frase": "Nós precisamos revisar esse documento com cuidado.", "traducao": "We need to review this document carefully." },
{ "frase": "Ele assumiu a responsabilidade pelo erro.", "traducao": "He took responsibility for the mistake." },
{ "frase": "Eu não estava preparado para essa mudança.", "traducao": "I was not prepared for this change." },
{ "frase": "Ela conseguiu resolver o problema sozinha.", "traducao": "She managed to solve the problem on her own." },
{ "frase": "Nós discutimos o assunto por mais de uma hora.", "traducao": "We discussed the issue for over an hour." },
{ "frase": "Ele demonstrou interesse no projeto.", "traducao": "He showed interest in the project." },
{ "frase": "Eu tive dificuldade em entender as instruções.", "traducao": "I had trouble understanding the instructions." },
{ "frase": "Ela decidiu adiar a decisão.", "traducao": "She decided to postpone the decision." },
{ "frase": "Nós estamos lidando com um prazo apertado.", "traducao": "We are dealing with a tight deadline." },
{ "frase": "Ele fez um comentário inesperado.", "traducao": "He made an unexpected comment." },
{ "frase": "Eu percebo uma melhora no meu inglês.", "traducao": "I notice an improvement in my English." },
{ "frase": "Ela sugeriu uma abordagem diferente.", "traducao": "She suggested a different approach." },
{ "frase": "Nós precisamos alinhar nossas expectativas.", "traducao": "We need to align our expectations." },
{ "frase": "Ele ficou satisfeito com o resultado final.", "traducao": "He was satisfied with the final result." },
{ "frase": "comi, como, comerei", "traducao": "ate, eat, will eat" },
{ "frase": "fui, vou, irei", "traducao": "went, go, will go" },
{ "frase": "fiz, faço, farei", "traducao": "did, do, will do" },
{ "frase": "vi, vejo, verei", "traducao": "saw, see, will see" },
{ "frase": "falei, falo, falarei", "traducao": "spoke, speak, will speak" },
{ "frase": "aprendi, aprendo, aprenderei", "traducao": "learned, learn, will learn" },
{ "frase": "trabalhei, trabalho, trabalharei", "traducao": "worked, work, will work" },
{ "frase": "estudei, estudo, estudarei", "traducao": "studied, study, will study" },
{ "frase": "comprei, compro, comprarei", "traducao": "bought, buy, will buy" },
{ "frase": "entendi, entendo, entenderei", "traducao": "understood, understand, will understand" },
{ "frase": "pensei, penso, pensarei", "traducao": "thought, think, will think" },
{ "frase": "escrevi, escrevo, escreverei", "traducao": "wrote, write, will write" },
{ "frase": "li, leio, lerei", "traducao": "read, read, will read" },
{ "frase": "dirigi, dirijo, dirigirei", "traducao": "drove, drive, will drive" },
{ "frase": "viajei, viajo, viajarei", "traducao": "traveled, travel, will travel" },
{ "frase": "ajudei, ajudo, ajudarei", "traducao": "helped, help, will help" },
{ "frase": "decidi, decido, decidirei", "traducao": "decided, decide, will decide" },
{ "frase": "perdi, perco, perderei", "traducao": "lost, lose, will lose" },
{ "frase": "ganhei, ganho, ganharei", "traducao": "won, win, will win" },
{ "frase": "cheguei, chego, chegarei", "traducao": "arrived, arrive, will arrive" },
{ "frase": "saí, saio, sairei", "traducao": "left, leave, will leave" },
{ "frase": "conheci, conheço, conhecerei", "traducao": "met, know, will know" },
{ "frase": "esqueci, esqueço, esquecerei", "traducao": "forgot, forget, will forget" },
{ "frase": "lembrei, lembro, lembrarei", "traducao": "remembered, remember, will remember" },
{ "frase": "tentei, tento, tentarei", "traducao": "tried, try, will try" },
{ "frase": "mudei, mudo, mudarei", "traducao": "changed, change, will change" },
{ "frase": "criei, crio, criarei", "traducao": "created, create, will create" },
{ "frase": "expliquei, explico, explicarei", "traducao": "explained, explain, will explain" },
{ "frase": "aceitei, aceito, aceitarei", "traducao": "accepted, accept, will accept" },
{ "frase": "terminei, termino, terminarei", "traducao": "finished, finish, will finish" }
],


    "italiano": [
        { "frase": "O céu está muito bonito hoje.", "traducao": "Il cielo è molto bello oggi." },
        { "frase": "Eu gosto de aprender coisas novas.", "traducao": "Mi piace imparare cose nuove." },
        { "frase": "Onde fica a biblioteca?", "traducao": "Dov'è la biblioteca?" },
        { "frase": "Eu preciso de um café.", "traducao": "Ho bisogno di un caffè." },
        { "frase": "Qual é o seu livro favorito?", "traducao": "Qual è il tuo libro preferito?" }
    ],
    "espanhol": [
        { "frase": "O céu está muito bonito hoje.", "traducao": "El cielo está muy hermoso hoy." },
        { "frase": "Eu preciso de um café.", "traducao": "Necesito un café." }
    ]
};