const basededados = {
    "ingles": [
        { "frase": "Eu gosto de aprender coisas novas.", "traducao": "I like to learn new things." },
{ "frase": "Ela trabalha perto de casa.", "traducao": "She works near home." },
{ "frase": "Nós estudamos inglês todos os dias.", "traducao": "We study English every day." },
{ "frase": "Ele precisa terminar o trabalho hoje.", "traducao": "He needs to finish the work today." },
{ "frase": "Eu acordei cedo esta manhã.", "traducao": "I woke up early this morning." },
{ "frase": "Eles moram em uma cidade pequena.", "traducao": "They live in a small city." },
{ "frase": "Nós vamos jantar fora hoje.", "traducao": "We are going to eat out today." },
{ "frase": "Ela gosta muito de música.", "traducao": "She really likes music." },
{ "frase": "Eu uso o computador para trabalhar.", "traducao": "I use the computer to work." },
{ "frase": "Ele chegou atrasado para a aula.", "traducao": "He arrived late for class." },
{ "frase": "Nós precisamos comprar comida.", "traducao": "We need to buy food." },
{ "frase": "Eu bebo café todas as manhãs.", "traducao": "I drink coffee every morning." },
{ "frase": "Ela falou com o professor.", "traducao": "She talked to the teacher." },
{ "frase": "Eles assistem TV à noite.", "traducao": "They watch TV at night." },
{ "frase": "Nós saímos mais cedo ontem.", "traducao": "We left earlier yesterday." },
{ "frase": "Nós precisamos alinhar nossas expectativas.", "traducao": "We need to align our expectations." },
{ "frase": "Ela ficou satisfeita com o resultado final.", "traducao": "She was satisfied with the final result." },
{ "frase": "Ele assumiu a responsabilidade pelo erro.", "traducao": "He took responsibility for the mistake." },
{ "frase": "Nós discutimos o problema com calma.", "traducao": "We discussed the problem calmly." },
{ "frase": "Eu percebi uma melhora no meu desempenho.", "traducao": "I noticed an improvement in my performance." },
{ "frase": "Ela sugeriu uma solução alternativa.", "traducao": "She suggested an alternative solution." },
{ "frase": "Nós estamos lidando com um prazo curto.", "traducao": "We are dealing with a short deadline." },
{ "frase": "Ele explicou a situação de forma clara.", "traducao": "He explained the situation clearly." },
{ "frase": "Eu tive dificuldade em entender o processo.", "traducao": "I had difficulty understanding the process." },
{ "frase": "Ela decidiu mudar de estratégia.", "traducao": "She decided to change her strategy." },
{ "frase": "Nós avaliamos todas as possibilidades.", "traducao": "We evaluated all the possibilities." },
{ "frase": "Ele demonstrou interesse no projeto.", "traducao": "He showed interest in the project." },
{ "frase": "Eu não concordei com a proposta.", "traducao": "I did not agree with the proposal." },
{ "frase": "Ela conseguiu resolver o problema rapidamente.", "traducao": "She managed to solve the problem quickly." },
{ "frase": "Nós precisamos melhorar nossa comunicação.", "traducao": "We need to improve our communication." },
        { "frase": "O céu está muito bonito hoje.", "traducao": "The sky is very beautiful today." },
        { "frase": "Eu gosto de aprender coisas novas.", "traducao": "I like to learn new things." },
        { "frase": "Onde fica a biblioteca?", "traducao": "Where is the library?" },
        { "frase": "Eu preciso de um café.", "traducao": "I need a coffee." },
        { "frase": "Qual é o seu livro favorito?", "traducao": "What is your favorite book?" },
        { "frase": "Eu esqueci de responder o e-mail ontem.", "traducao": "I forgot to reply to the email yesterday." },
{ "frase": "Ela está tentando aprender uma nova habilidade.", "traducao": "She is trying to learn a new skill." },
{ "frase": "Nós precisamos tomar uma decisão em breve.", "traducao": "We need to make a decision soon." },
{ "frase": "Ele ficou surpreso com o resultado da reunião.", "traducao": "He was surprised by the outcome of the meeting." },
{ "frase": "Eu não concordo totalmente com essa ideia.", "traducao": "I don’t completely agree with this idea." },
{ "frase": "Eles cancelaram a viagem por causa do clima.", "traducao": "They canceled the trip because of the weather." },
{ "frase": "Estou procurando uma solução mais eficiente.", "traducao": "I am looking for a more efficient solution." },
{ "frase": "Ela se sente confiante sobre a apresentação.", "traducao": "She feels confident about the presentation." },
{ "frase": "Nós acabamos perdendo o último ônibus.", "traducao": "We ended up missing the last bus." },
{ "frase": "Ele prefere trabalhar sozinho à noite.", "traducao": "He prefers to work alone at night." },
{ "frase": "Eu percebi um erro no relatório.", "traducao": "I noticed a mistake in the report." },
{ "frase": "Ela explicou a situação com muita clareza.", "traducao": "She explained the situation very clearly." },
{ "frase": "Nós estamos acostumados a lidar com pressão.", "traducao": "We are used to dealing with pressure." },
{ "frase": "Ele hesitou antes de aceitar a proposta.", "traducao": "He hesitated before accepting the offer." },
{ "frase": "Eu estou tentando equilibrar trabalho e vida pessoal.", "traducao": "I am trying to balance work and personal life." },
{ "frase": "Ela ficou frustrada com a falta de progresso.", "traducao": "She got frustrated with the lack of progress." },
{ "frase": "Nós precisamos revisar esse documento com cuidado.", "traducao": "We need to review this document carefully." },
{ "frase": "Ele assumiu a responsabilidade pelo erro.", "traducao": "He took responsibility for the mistake." },
{ "frase": "Eu não estava preparado para essa mudança.", "traducao": "I was not prepared for this change." },
{ "frase": "Ela conseguiu resolver o problema sozinha.", "traducao": "She managed to solve the problem on her own." },
{ "frase": "Nós discutimos o assunto por mais de uma hora.", "traducao": "We discussed the issue for over an hour." },
{ "frase": "Ele demonstrou interesse no projeto.", "traducao": "He showed interest in the project." },
{ "frase": "Eu tive dificuldade em entender as instruções.", "traducao": "I had trouble understanding the instructions." },
{ "frase": "Ela decidiu adiar a decisão.", "traducao": "She decided to postpone the decision." },
{ "frase": "Nós estamos lidando com um prazo apertado.", "traducao": "We are dealing with a tight deadline." },
{ "frase": "Ele fez um comentário inesperado.", "traducao": "He made an unexpected comment." },
{ "frase": "Eu percebo uma melhora no meu inglês.", "traducao": "I notice an improvement in my English." },
{ "frase": "Ela sugeriu uma abordagem diferente.", "traducao": "She suggested a different approach." },
{ "frase": "Nós precisamos alinhar nossas expectativas.", "traducao": "We need to align our expectations." },
{ "frase": "Ele ficou satisfeito com o resultado final.", "traducao": "He was satisfied with the final result." },
],

"frases":[
    { "frase": "Eu percebi que precisava mudar minha rotina para melhorar minha qualidade de vida.", "traducao": "I realized that I needed to change my routine to improve my quality of life; I realize that I need to change my routine to improve my quality of life; I will realize that I need to change my routine to improve my quality of life" },
{ "frase": "Ela explicou o problema com calma para evitar conflitos desnecessários.", "traducao": "She explained the problem calmly to avoid unnecessary conflicts; She explains the problem calmly to avoid unnecessary conflicts; She will explain the problem calmly to avoid unnecessary conflicts" },
{ "frase": "Nós discutimos várias opções antes de tomar uma decisão importante.", "traducao": "We discussed several options before making an important decision; We discuss several options before making an important decision; We will discuss several options before making an important decision" },
{ "frase": "Ele percebeu que havia cometido um erro ao analisar os dados.", "traducao": "He realized that he had made a mistake when analyzing the data; He realizes that he has made a mistake when analyzing the data; He will realize that he will have made a mistake when analyzing the data" },
{ "frase": "Eu precisei reorganizar minhas prioridades depois daquela conversa.", "traducao": "I needed to reorganize my priorities after that conversation; I need to reorganize my priorities after that conversation; I will need to reorganize my priorities after that conversation" },
{ "frase": "Ela decidiu adiar o projeto porque não se sentia preparada.", "traducao": "She decided to postpone the project because she did not feel ready; She decides to postpone the project because she does not feel ready; She will decide to postpone the project because she will not feel ready" },
{ "frase": "Nós aprendemos a importância da comunicação clara no trabalho.", "traducao": "We learned the importance of clear communication at work; We learn the importance of clear communication at work; We will learn the importance of clear communication at work" },
{ "frase": "Ele tentou resolver o problema sozinho para ganhar mais confiança.", "traducao": "He tried to solve the problem on his own to gain more confidence; He tries to solve the problem on his own to gain more confidence; He will try to solve the problem on his own to gain more confidence" },
{ "frase": "Eu fiquei frustrado quando os resultados não corresponderam às expectativas.", "traducao": "I got frustrated when the results did not match the expectations; I get frustrated when the results do not match the expectations; I will get frustrated when the results do not match the expectations" },
{ "frase": "Ela percebeu que precisava estudar mais para alcançar seus objetivos.", "traducao": "She realized that she needed to study more to achieve her goals; She realizes that she needs to study more to achieve her goals; She will realize that she needs to study more to achieve her goals" },
{ "frase": "Nós assumimos mais responsabilidades após a mudança na equipe.", "traducao": "We took on more responsibilities after the change in the team; We take on more responsibilities after the change in the team; We will take on more responsibilities after the change in the team" },
{ "frase": "Ele explicou suas ideias de forma clara para convencer os colegas.", "traducao": "He explained his ideas clearly to convince his colleagues; He explains his ideas clearly to convince his colleagues; He will explain his ideas clearly to convince his colleagues" },
{ "frase": "Eu percebi uma melhora significativa depois de mudar meus hábitos.", "traducao": "I noticed a significant improvement after changing my habits; I notice a significant improvement after changing my habits; I will notice a significant improvement after changing my habits" },
{ "frase": "Ela analisou cuidadosamente os riscos antes de aceitar a proposta.", "traducao": "She carefully analyzed the risks before accepting the proposal; She carefully analyzes the risks before accepting the proposal; She will carefully analyze the risks before accepting the proposal" },
{ "frase": "Nós enfrentamos dificuldades inesperadas durante o processo.", "traducao": "We faced unexpected difficulties during the process; We face unexpected difficulties during the process; We will face unexpected difficulties during the process" },
{ "frase": "Ele percebeu que precisava melhorar sua gestão de tempo.", "traducao": "He realized that he needed to improve his time management; He realizes that he needs to improve his time management; He will realize that he needs to improve his time management" },
{ "frase": "Eu precisei adaptar meus planos por causa das circunstâncias.", "traducao": "I had to adapt my plans because of the circumstances; I have to adapt my plans because of the circumstances; I will have to adapt my plans because of the circumstances" },
{ "frase": "Ela compartilhou sua experiência para ajudar outras pessoas.", "traducao": "She shared her experience to help other people; She shares her experience to help other people; She will share her experience to help other people" },
{ "frase": "Nós avaliamos os resultados para identificar possíveis melhorias.", "traducao": "We evaluated the results to identify possible improvements; We evaluate the results to identify possible improvements; We will evaluate the results to identify possible improvements" },
{ "frase": "Ele decidiu mudar de abordagem após receber o feedback.", "traducao": "He decided to change his approach after receiving the feedback; He decides to change his approach after receiving the feedback; He will decide to change his approach after receiving the feedback" }
],

"verbosIngles":[
    { "frase": "comi, como, comerei", "traducao": "ate, eat, will eat" },
{ "frase": "fui, vou, irei", "traducao": "went, go, will go" },
{ "frase": "fiz, faço, farei", "traducao": "did, do, will do" },
{ "frase": "vi, vejo, verei", "traducao": "saw, see, will see" },
{ "frase": "falei, falo, falarei", "traducao": "spoke, speak, will speak" },
{ "frase": "aprendi, aprendo, aprenderei", "traducao": "learned, learn, will learn" },
{ "frase": "trabalhei, trabalho, trabalharei", "traducao": "worked, work, will work" },
{ "frase": "estudei, estudo, estudarei", "traducao": "studied, study, will study" },
{ "frase": "comprei, compro, comprarei", "traducao": "bought, buy, will buy" },
{ "frase": "entendi, entendo, entenderei", "traducao": "understood, understand, will understand" },
{ "frase": "pensei, penso, pensarei", "traducao": "thought, think, will think" },
{ "frase": "escrevi, escrevo, escreverei", "traducao": "wrote, write, will write" },
{ "frase": "li, leio, lerei", "traducao": "read, read, will read" },
{ "frase": "dirigi, dirijo, dirigirei", "traducao": "drove, drive, will drive" },
{ "frase": "viajei, viajo, viajarei", "traducao": "traveled, travel, will travel" },
{ "frase": "ajudei, ajudo, ajudarei", "traducao": "helped, help, will help" },
{ "frase": "decidi, decido, decidirei", "traducao": "decided, decide, will decide" },
{ "frase": "perdi, perco, perderei", "traducao": "lost, lose, will lose" },
{ "frase": "ganhei, ganho, ganharei", "traducao": "won, win, will win" },
{ "frase": "cheguei, chego, chegarei", "traducao": "arrived, arrive, will arrive" },
{ "frase": "saí, saio, sairei", "traducao": "left, leave, will leave" },
{ "frase": "conheci, conheço, conhecerei", "traducao": "met, know, will know" },
{ "frase": "esqueci, esqueço, esquecerei", "traducao": "forgot, forget, will forget" },
{ "frase": "lembrei, lembro, lembrarei", "traducao": "remembered, remember, will remember" },
{ "frase": "tentei, tento, tentarei", "traducao": "tried, try, will try" },
{ "frase": "mudei, mudo, mudarei", "traducao": "changed, change, will change" },
{ "frase": "criei, crio, criarei", "traducao": "created, create, will create" },
{ "frase": "expliquei, explico, explicarei", "traducao": "explained, explain, will explain" },
{ "frase": "aceitei, aceito, aceitarei", "traducao": "accepted, accept, will accept" },
{ "frase": "terminei, termino, terminarei", "traducao": "finished, finish, will finish" },
{ "frase": "andei, ando, andarei", "traducao": "walked, walk, will walk" },
{ "frase": "corri, corro, correrei", "traducao": "ran, run, will run" },
{ "frase": "brinquei, brinco, brincarei", "traducao": "played, play, will play" },
{ "frase": "olhei, olho, olharei", "traducao": "looked, look, will look" },
{ "frase": "usei, uso, usarei", "traducao": "used, use, will use" },
{ "frase": "abri, abro, abrirei", "traducao": "opened, open, will open" },
{ "frase": "fechei, fecho, fecharei", "traducao": "closed, close, will close" },
{ "frase": "gostei, gosto, gostarei", "traducao": "liked, like, will like" },
{ "frase": "chamei, chamo, chamarei", "traducao": "called, call, will call" },
{ "frase": "esperei, espero, esperarei", "traducao": "waited, wait, will wait" },
{ "frase": "entrei, entro, entrarei", "traducao": "entered, enter, will enter" },
{ "frase": "saí, saio, sairei", "traducao": "left, leave, will leave" },
{ "frase": "paguei, pago, pagarei", "traducao": "paid, pay, will pay" },
{ "frase": "mudei, mudo, mudarei", "traducao": "changed, change, will change" },
{ "frase": "ajudei, ajudo, ajudarei", "traducao": "helped, help, will help" },
{ "frase": "escolhi, escolho, escolherei", "traducao": "chose, choose, will choose" },
{ "frase": "construí, construo, construirei", "traducao": "built, build, will build" },
{ "frase": "melhorei, melhoro, melhorarei", "traducao": "improved, improve, will improve" },
{ "frase": "organizei, organizo, organizarei", "traducao": "organized, organize, will organize" },
{ "frase": "planejei, planejo, planejarei", "traducao": "planned, plan, will plan" },
{ "frase": "evitei, evito, evitarei", "traducao": "avoided, avoid, will avoid" },
{ "frase": "considerei, considero, considerarei", "traducao": "considered, consider, will consider" },
{ "frase": "resolvi, resolvo, resolverei", "traducao": "solved, solve, will solve" },
{ "frase": "aceitei, aceito, aceitarei", "traducao": "accepted, accept, will accept" },
{ "frase": "rejeitei, rejeito, rejeitarei", "traducao": "rejected, reject, will reject" },
{ "frase": "observei, observo, observarei", "traducao": "observed, observe, will observe" },
{ "frase": "analisei, analiso, analisarei", "traducao": "analyzed, analyze, will analyze" },
{ "frase": "concluí, concluo, concluirei", "traducao": "concluded, conclude, will conclude" },
{ "frase": "assumi, assumo, assumirei", "traducao": "took on, take on, will take on" },
{ "frase": "negociei, negocio, negociarei", "traducao": "negotiated, negotiate, will negotiate" }
],

    "italiano": [
        { "frase": "O céu está muito bonito hoje.", "traducao": "Il cielo è molto bello oggi." },
        { "frase": "Eu gosto de aprender coisas novas.", "traducao": "Mi piace imparare cose nuove." },
        { "frase": "Onde fica a biblioteca?", "traducao": "Dov'è la biblioteca?" },
        { "frase": "Eu preciso de um café.", "traducao": "Ho bisogno di un caffè." },
        { "frase": "Qual é o seu livro favorito?", "traducao": "Qual è il tuo libro preferito?" }
    ],
    "espanhol": [
        { "frase": "O céu está muito bonito hoje.", "traducao": "El cielo está muy hermoso hoy." },
        { "frase": "Eu preciso de um café.", "traducao": "Necesito un café." }
    ]
};